### ISSUE TITLE
Update data representations and query by ID

### ISSUE THREAD

**Issue by armsnyder** [eecs394-spr15/StockMyBar#44]
We should soon update our code throughout to use objectID as primary key

**Comment by missfxhr** [comment]
I have almost done this part. Currently I am cleaning some redundant codes, I will quote them first in "" and to see whether it will affect the whole app.

**Comment by missfxhr** [comment]
@friendly-flame What do you mean by "update data representations"?
I have finished the query by id part and I am fixing bugs.

**Comment by armsnyder** [comment]
What I meant is that in general throughout the code we should represent lists of ingredients and lists of recipes as lists of objects that contain fields like objectID and name. For instance, right now our barContents variable keeps a list of ingredient names. This should be changed to a list of javascript objects containing both the ingredient name and the ingredient objectID.

**Comment by missfxhr** [comment]
Oh if that is it. I think I have done it! barContents is already a list of ids. Also the cloudcode is now doing query by ids. Besides, I am also fixing other part of codes where name instead of id is used, including the filter file you wrote. So if i have question about that I will ask you later. Thanks. @friendly-flame

**Comment by armsnyder** [comment]
Cool, thanks for doing that!
